name: Sync Notion to GitHub

on:
  workflow_dispatch: # Ręczne uruchamianie z GitHub UI
  schedule:
    - cron: '0 3 * * *' # Codziennie o 03:00 UTC

jobs:
  sync-notion:
    runs-on: ubuntu-latest
    env:
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install @notionhq/client notion-to-md

      - name: Create docs folder
        run: mkdir -p docs

      - name: Export Notion pages
        run: node export-notion.js

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/*.md || true
          git commit -m "Update from Notion" || echo "No changes to commit"
          git push
